version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: preinstall.sh
      timeout: 200
  AfterInstall:
    - location: postinstall.sh
      timeout: 200
